### ISSUE TITLE
Getting a CherryPy error using Web handler

### ISSUE THREAD

**Issue by killian441** [nio-blocks/web_handler#5]
```
[2016-12-02 23:20:11.014] NIO [ERROR] [SlackRandomChatter.cherrypy-error] [02/Dec/2016:16:20:11] HTTP
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 54, in index
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 64, in _call_handler
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 138, in _do_callback
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 147, in _handle_response_headers
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/nio/modules/settings/settings.py", line 26, in get
    raise NotImplementedError()
NotImplementedError
```

WebHandler has the correct output, but WebOutput doesn't seem to respond out.

**Comment by mattdodge** [comment]
This is likely a binary and framework mismatch. Can you post the output if you hit this URL:
http://localhost:8181/nio (or whatever host your n.io instance is running on).

**Comment by killian441** [comment]
The output is so:
```
{
    "start_time": "2016-12-05 13:35:43.055023",
    "modules": {},
    "nio": {
        "build": "20160906",
        "binary": "nio_full",
        "version": "2.0.0b10"
    },
    "components": {
        "RESTManager": {},
        "BlockManager": {},
        "ServiceMonitor": {},
        "LogManager": {},
        "ServiceManager": {},
        "ManagementPublisher": {},
        "ProjectManager": {},
        "ConfigMonitor": {},
        "ZmqCommunicationAPIManager": {}
    }
}
```

I seem to remember updating everything through pip at some point recently, but I had to roll back the framework(?) to 2.0.0.b10 because the more recent versions didn't work with the binary I have.

**Comment by mattdodge** [comment]
According to the [n.io releases page](https://github.com/nioinnovation/nio/releases) the Sept 6 binary should probably work with b11 framework. Try upgrading to that framework version and see if it's better?

```bash
pip install -U nio==2.0.0b11
```

**Comment by killian441** [comment]
I upgraded to b11 and got the same error. I also upgraded to the b12 framework and the service would not even start, here is that error: 
```[2016-12-06 17:25:42.057] NIO [ERROR] [main.cherrypy-error] [06/Dec/2016:10:25:42] HTTP
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cherrypy/_cprequest.py", line 670, in respond
    response.body = self.handler()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cherrypy/lib/encoding.py", line 217, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/cherrypy/_cpdispatch.py", line 61, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/rest.py", line 60, in index_id
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 64, in _call_handler
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 138, in _do_callback
  File "/var/lib/jenkins/jobs/nio Core/workspace/deployment/dist/nio_full-20160906-py3-none-any.whl-ext/niocore/modules/web/cherrypy/handler.py", line 152, in _handle_response_headers
AttributeError: 'RESTResourceCollectionHandler' object has no attribute 'get_allowed_methods'```

**Comment by killian441** [comment]
After upgrading to the latest version things are working. Looks like it was a version mismatch.
